version: '3'

services:
  db:
    image: mysql
    ports:
      - "3307:3307"
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: doug_server
    volumes:
      - .:/code
    ports:
      - "8765:8765"
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: "@.SenhaDoDb1.."