# Generated by Django 2.1.5 on 2019-03-12 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boletim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('data_upload', models.DateField()),
                ('disponivel_em', models.URLField()),
                ('data_boletim', models.DateField()),
                ('titulo_boletim', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contato', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('curso', models.ForeignKey(null=True, on_delete=None, related_name='departamento', to='doug_server_app.Curso')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('carga_horaria', models.IntegerField()),
                ('dia_da_semana', models.CharField(max_length=300)),
                ('semestre', models.IntegerField(choices=[(1, 2)])),
                ('ano', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('data_upload', models.DateField()),
                ('disponivel_em', models.URLField()),
                ('path', models.URLField()),
                ('informacao_adicional', models.CharField(max_length=200)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('data_upload', models.DateField()),
                ('disponivel_em', models.URLField()),
                ('titutlo', models.CharField(max_length=200)),
                ('corpo', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('lates', models.URLField()),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corpo_docente', to='doug_server_app.Departamento')),
                ('is_chefe_departamento', models.OneToOneField(null=True, on_delete=None, related_name='chefe_departamento', to='doug_server_app.Departamento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('curso', models.OneToOneField(null=True, on_delete=None, related_name='secretaria', to='doug_server_app.Curso')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Secretario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('secretaria', models.ForeignKey(null=True, on_delete=None, related_name='secretario', to='doug_server_app.Secretaria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tutores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True)),
                ('disciplina', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doug_server_app.Disciplinas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='professor_id',
            field=models.OneToOneField(on_delete=None, to='doug_server_app.Professor'),
        ),
        migrations.AddField(
            model_name='boletim',
            name='noticias_fk',
            field=models.ForeignKey(on_delete=None, to='doug_server_app.Noticia'),
        ),
        migrations.AddField(
            model_name='boletim',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
