# Generated by Django 2.1.5 on 2019-03-14 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doug_server_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletim',
            name='data_upload',
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='disponivel_em',
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='titulo_boletim',
        ),
        migrations.RemoveField(
            model_name='boletim',
            name='user',
        ),
    ]
