# Generated by Django 2.1.5 on 2019-01-27 02:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doug_server_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('carga_horaria', models.IntegerField()),
                ('calendario', models.DateField()),
                ('semestre', models.IntegerField(choices=[(1, 2)])),
                ('professor_id', models.OneToOneField(on_delete=None, to='doug_server_app.Professor')),
            ],
        ),
        migrations.CreateModel(
            name='Editais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('path', models.URLField()),
                ('data', models.DateField()),
                ('informacao_adicional', models.CharField(max_length=200)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
