# Generated by Django 2.1.5 on 2019-01-27 02:12

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('doug_server_app', '0002_added_disciplinas_editais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('telefone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True)),
                ('disciplina', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doug_server_app.Disciplinas')),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='lates',
            field=models.URLField(null=True),
        ),
    ]
