# Generated by Django 2.1.5 on 2019-03-14 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doug_server_app', '0002_auto_20190314_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boletim',
            name='noticias_fk',
        ),
        migrations.AddField(
            model_name='boletim',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='boletim_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doug_server_app.Boletim'),
        ),
    ]
