# Generated by Django 2.1.5 on 2019-03-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doug_server_app', '0003_auto_20190314_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='titutlo',
        ),
        migrations.AddField(
            model_name='edital',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='edital',
            name='nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
