# Generated by Django 2.1.5 on 2019-03-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doug_server_app', '0004_auto_20190319_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edital',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='nome',
        ),
    ]
