# Generated by Django 2.1.5 on 2019-01-30 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doug_server_app', '0005_auto_20190129_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='chefe_departamento',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='corpo_docente',
        ),
        migrations.AddField(
            model_name='professor',
            name='chefe_departamento',
            field=models.OneToOneField(null=True, on_delete=None, related_name='chefe_departamento', to='doug_server_app.Departamento'),
        ),
        migrations.AddField(
            model_name='professor',
            name='corpo_docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corpo_docente', to='doug_server_app.Departamento'),
        ),
    ]
