# Generated by Django 2.1.5 on 2019-01-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doug_server_app', '0006_auto_20190129_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='corpo_docente',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='chefe_departamento',
            new_name='is_chefe_departamento',
        ),
    ]
