# Generated by Django 2.1.5 on 2019-03-20 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doug_server_app', '0006_correcao_cardinalidade_usuario_e_noticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edital',
            name='user',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='user',
        ),
    ]
