# Generated by Django 2.1.5 on 2019-01-30 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doug_server_app', '0007_auto_20190130_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretaria',
            name='secretario',
        ),
        migrations.AddField(
            model_name='secretaria',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secretario',
            name='secretaria',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secretario', to='doug_server_app.Secretaria'),
        ),
    ]
