# Generated by Django 2.1.5 on 2019-01-31 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doug_server_app', '0008_change_pk_from_secretario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='departamento_fk',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='secretaria_fk',
        ),
        migrations.AddField(
            model_name='departamento',
            name='curso',
            field=models.OneToOneField(null=True, on_delete=None, related_name='departamento', to='doug_server_app.Curso'),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='curso',
            field=models.OneToOneField(null=True, on_delete=None, related_name='secretario', to='doug_server_app.Curso'),
        ),
    ]
