# Generated by Django 2.1.5 on 2019-03-20 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doug_server_app', '0008_auto_20190320_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boletim',
            old_name='data_boletim',
            new_name='data',
        ),
    ]
