# Generated by Django 2.1.5 on 2019-01-31 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doug_server_app', '0009_added_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretario',
            name='secretaria',
            field=models.OneToOneField(null=True, on_delete=None, related_name='secretario', to='doug_server_app.Secretaria'),
        ),
    ]
