# Generated by Django 2.1.5 on 2019-07-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doug_server_app', '0010_change_boletim_titulo_field_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='titulo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
