# Generated by Django 2.1.5 on 2019-07-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doug_server_app', '0011_auto_20190718_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='lates',
            new_name='lattes',
        ),
    ]
