# Generated by Django 2.1.5 on 2019-07-29 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doug_server_app', '0012_change_lates_to_lattes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='disciplinas',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='nome',
        ),
    ]
