# Generated by Django 2.1.5 on 2019-07-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doug_server_app', '0013_pessoa_nome_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='nome',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='nome',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='secretario',
            name='nome',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tutores',
            name='nome',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
