# Generated by Django 2.1.5 on 2019-08-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doug_server_app', '0015_auto_20190729_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=30, null=True)),
                ('assunto', models.TextField()),
                ('data_criado', models.DateField()),
                ('data_evento', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
