# Generated by Django 2.1.5 on 2019-08-14 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doug_server_app', '0017_added_eventos_to_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_criado',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
