# Generated by Django 2.1.5 on 2019-08-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doug_server_app', '0018_data_criado_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_criado',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_evento',
            field=models.DateTimeField(),
        ),
    ]
